### ISSUE TITLE
save changes seems inactive

### ISSUE THREAD

**Issue by bourgeoa** [melvincarvalho/solid-bookmark#2]
I use your updated exemple
and go to Markbook.org 
After logging to my pod I create a bookmark, click "save changes" and
it doesn't save anything to my /public/bookmarks.ttl file

the address is   https://markbook.org/#

**Comment by melvincarvalho** [comment]
Thanks for trying it -- can you wait a day or so, I'm just fixing some bugs

**Comment by melvincarvalho** [comment]
I've done quite a big refactor

While still a work in progress, it should be better now, and easier to debug

**Comment by melvincarvalho** [comment]
I've moved this work to it's own repo :

**Comment by melvincarvalho** [comment]
https://github.com/mark-book/markbook
